@startuml UCD_1.1

right header
<font size=24 color=black>Package: <b>UCD_1.1

end header

title
<font size=18 color=black>Аналітичний портал
<font size=16 color=black>Діаграма прецедентів 
end title


actor "Менеджер проекту" as Manager
actor "Замовник проекту" as Client
actor "Адміністратор" as Admin
actor "Робітник" as Worker

usecase "<b>UC_1</b>\nСтворення плану\nпроекту" as UC_1
usecase "<b>UC_2</b>\nЗміна плану \nпроекту" as UC_2
usecase "<b>UC_3</b>\nПерегляд плану \nпроекту" as UC_3
usecase "<b>UC_4</b>\nДодавання робітника" as UC_4
usecase "<b>UC_5</b>\nВстановлення ієрархії \nробітників" as UC_5
usecase "<b>UC_6</b>\nCтворення задачі" as UC_6
usecase "<b>UC_7</b>\nЗакріплення виконавця \nзадачі" as UC_7
usecase "<b>UC_8</b>\nЗакріплення ревьюєра\nзадачі" as UC_8
usecase "<b>UC_9</b>\nЗдача задачі" as UC_9
usecase "<b>UC_10</b>\nПідтвердження виконання \nзадачі" as UC_10

Client -> UC_3

Admin -> UC_4
Admin -l-> UC_5

Worker -l-> UC_6
Worker -u-> UC_7
Worker -u--> UC_8
Worker -u-> UC_9
Worker -r-> UC_10

Manager -u-|> Worker
Manager -d-|> Client

Manager -l-> UC_1
Manager -r-> UC_2



right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020 
end footer


@enduml

@startuml UC_1

left header
<font color=000 size=18><b>Package:</b> UCD_1

<font color=000 size=16><b>ID:</b> UC_1
<font color=000 size=16><b>Назва:</b> Створення плану проекту
<font color=000 size=16><b>Учасники:</b> Менеджер проекту, Система
<font color=000 size=16><b>Передумови:</b> План проекту не створений
<font color=000 size=16><b>Результат:</b> План проекту створений
<font color=000 size=16><b>Виключні ситуації:</b> Відсутні

<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Менеджер проекту|
start
:Встановлює правила
комунікації в проекті;

|Система|
:Зберігає параметри;
:Формує план проекту;
|Менеджер проекту|
stop

right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020 
end footer

@enduml

@startuml UC_2

left header
<font color=000 size=18><b>Package:</b> UCD_1.1

<font color=000 size=16><b>ID:</b> UC_2
<font color=000 size=16><b>Назва:</b> Зміна плану проекту
<font color=000 size=16><b>Учасники:</b> Менеджер проекту, Система
<font color=000 size=16><b>Передумови:</b> План проекту не створений.
<font color=000 size=16><b>Результат:</b> Формується новий план проекту.
<font color=000 size=16><b>Виключні ситуації:</b> Відсутні

<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Менеджер проекту|
start
:Надсилає запит до системи 
щодо перегляду плану проекту;

|Система|
:Надсилає план проекту;
|Менеджер проекту|
:Обирає пункт "Редагувати";
:Редагує поля які потребують змін;
|Система|
:Система зберігає параметри;
:Формує новий план проекту;
|Менеджер проекту|
stop

right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020 
end footer

@enduml

@startuml UC_3

left header
<font color=000 size=18><b>Package:</b> UCD_1.1
<font color=000 size=16><b>ID:</b> UC_3
<font color=000 size=16><b>Назва:</b> Перегляд плану проекту
<font color=000 size=16><b>Учасники:</b> Користувач, Система
<font color=000 size=16><b>Передумови:</b> Користувач має доступ для перегляду плану проекту
<font color=000 size=16><b>Результат:</b> План проекту
<font color=000 size=16><b>Виключні ситуації:</b> EX_1 Недостатні права для перегляду
<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Користувач|
start
:Обирає пункт 
"Перегляд плану проекту" 
в інтерфейсі користувача;
|Система|
:Перевіряє чи має користувач 
доступ для перегляду плану проекту;

note right #aaffaa 

<font color=red><b> Може виникнути EX_1

end note

: Надсилає дані із посиланнями 
на сформовані звіти;

|Користувач|
stop;

right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020 
end footer

@enduml

@startuml UC_4

left header
<font color=000 size=18><b>Package:</b> UCD_1.1
<font color=000 size=16><b>ID:</b> UC_4
<font color=000 size=16><b>Назва:</b> Додавання робітника
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система
<font color=000 size=16><b>Передумови:</b> Відсутні
<font color=000 size=16><b>Результат:</b> Робітник доданий до списку
<font color=000 size=16><b>Виключні ситуації:</b> Відсутні
<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Адміністратор|
start
:Запитує список робітників;
|Система|
:надсилає поточний 
список робітників;
|Адміністратор|
:Обирає опцію 
"Додати робітника";
:вводить інформацію 
про нового робітника;
|Система|
:Додає нового робітника
до списку робітників;
|Адміністратор|
stop;

right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020 
end footer

@enduml

@startuml UC_5

left header
<font color=000 size=18><b>Package:</b> UCD_1.1
<font color=000 size=16><b>ID:</b> UC_5
<font color=000 size=16><b>Назва:</b> Встановлення ієрархії робітників
<font color=000 size=16><b>Учасники:</b> Адміністратор, Система
<font color=000 size=16><b>Передумови:</b> Відсутні
<font color=000 size=16><b>Результат:</b> Робітник доданий до списку
<font color=000 size=16><b>Виключні ситуації:</b> Відсутні
<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Адміністратор|
start
:Запитує список робітників;
|Система|
:надсилає поточний 
список робітників;
|Адміністратор|
:Обирає робітника;
:Встановлює робітника,
якому підпорядковується
даний робітник;
:Встановлює робітників,
які підпорядковуються
даному робітнику;
|Система|
:Зберігає дані;
|Адміністратор|
stop;

right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020 
end footer

@enduml

@startuml UC_6

left header
<font color=000 size=18><b>Package:</b> UCD_1.1
<font color=000 size=16><b>ID:</b> UC_6
<font color=000 size=16><b>Назва:</b> Створення задачі
<font color=000 size=16><b>Учасники:</b> Робітник, Система
<font color=000 size=16><b>Передумови:</b> Відсутні
<font color=000 size=16><b>Результат:</b> Задача додана до списку очікуючих задач
<font color=000 size=16><b>Виключні ситуації:</b> Відсутні
<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Робітник|
start
:Формує задачу 
і надсилає до системи;
|Система|
:Додає задачу у список 
очікуючих задач для робітників,
які йому підпорядковуються;
:встановлює стан задачі на 
"Очікує виконавця";
:надсилає повідомлення 
до підпорядованих робітників 
щодо нової задачі;
|Робітник|
stop;

right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020 
end footer

@enduml


@startuml UC_7

left header
<font color=000 size=18><b>Package:</b> UCD_1.1
<font color=000 size=16><b>ID:</b> UC_7
<font color=000 size=16><b>Назва:</b> Закріплення виконавця задачі
<font color=000 size=16><b>Учасники:</b> Робітник, Система
<font color=000 size=16><b>Передумови:</b> Відсутні
<font color=000 size=16><b>Результат:</b> Задача закріплена за виконавцем
<font color=000 size=16><b>Виключні ситуації:</b> Відсутні
<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Робітник|
start
:Обирає задачу 
зі списку очікуючих задач 
і яка знаходиться в стані
"Очікує виконавця";
:Обирає опцію 
"Стати виконавцем задачі";
|Система|
:Закріплює робітника 
як виконавця задачі;
:Встановлює стан задачі 
на "Очікує ревьюєра";
|Робітник|
stop;

right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020 
end footer

@enduml

@startuml UC_8

left header
<font color=000 size=18><b>Package:</b> UCD_1.1
<font color=000 size=16><b>ID:</b> UC_8
<font color=000 size=16><b>Назва:</b> Закріплення ревьюєра задачі
<font color=000 size=16><b>Учасники:</b> Робітник, Система
<font color=000 size=16><b>Передумови:</b> Відсутні
<font color=000 size=16><b>Результат:</b> Задача закріплена за ревьюєром
<font color=000 size=16><b>Виключні ситуації:</b> Відсутні
<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Робітник|
start
:Обирає задачу 
зі списку очікуючих задач 
і яка знаходиться в стані
"Очікує ревьюєра";
:Обирає опцію 
"Стати ревьюєром задачі";
|Система|
:Закріплює робітника 
як ревьюєра задачі;
:Встановлює стан задачі 
на "Виконується";
:Вилучає задачу 
зі списку очікуючих задач;
|Робітник|
stop;

right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020 
end footer

@enduml

@startuml UC_9

left header
<font color=000 size=18><b>Package:</b> UCD_1.1
<font color=000 size=16><b>ID:</b> UC_9
<font color=000 size=16><b>Назва:</b> Виконання задачі
<font color=000 size=16><b>Учасники:</b> Робітник, Система
<font color=000 size=16><b>Передумови:</b> Робітник закріплений як виконавець задачі
<font color=000 size=16><b>Результат:</b> Задача в стані "Очікує підтвердження"
<font color=000 size=16><b>Виключні ситуації:</b> Відсутні
<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Робітник|
start
:Відкриває інтерфейс
виконання задачі;
:Додає артефакти виконання задачі;
:Обирає опцію 
"Завершити задачу";
|Система|
:Зберігає артефакти 
виконання задачі;
:Встановлює стан задачі 
на "Очікує підтвердження";
:Надсилає повідомлення 
до ревьюєра задачі 
щодо очікування на 
підтвердження 
виконання задачі;
|Робітник|
stop;

right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020 
end footer

@enduml

@startuml UC_10

left header
<font color=000 size=18><b>Package:</b> UCD_1.1
<font color=000 size=16><b>ID:</b> UC_9
<font color=000 size=16><b>Назва:</b> Виконання задачі
<font color=000 size=16><b>Учасники:</b> Робітник, Система
<font color=000 size=16><b>Передумови:</b> Робітник закріплений як ревьюєр задачі
<font color=000 size=16><b>Результат:</b> Задача в стані "Очікує підтвердження"
<font color=000 size=16><b>Виключні ситуації:</b> EX_2 Ревьюєр не підтверджує
<font color=000 size=16> виконання задачі: Задача посилається на доробку
<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Робітник|
start
:Обирає задачу із списку на огляд;
:Ознайомлюється із 
артефактами виконання задачі;
:Підтверджує виконання задачі;
note #aaffaa 

<font color=red><b> Може виникнути EX_2

end note
|Система|
:Встановлює стан задачі 
на "Виконано";
:Надсилає повідомлення 
до замовника задачі 
щодо виконання задачі;
|Робітник|
stop;

right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020 
end footer

@enduml